### ISSUE TITLE
디자인 수정 부탁

### ISSUE THREAD

**Issue by zion830** [3dollar-in-my-pocket/3dollars-in-my-pocket-intro#2]
* Contact info 
    * 밑에 `가슴속 3천원~ 최선을 다하고 있습니다` - 가운데 정렬
    * `이름, 이메일 ,전하고 싶은 말씀을 적어주세요` - noto sans 적용 안됨
* Home
    * 리뷰중에 `회사끝나고~정말생겼네요!!` 닉네임 잘려서 안나옴
    * 카테고리 바로가기 << 삭제해야함
    * 지도 설명 `지도에서 ~ 다섯개의 가게를 바로 만나볼 수 있어요.` -> 메인페이지에서 가장 가까운 가게를 확인할 수 있어요!
    * iOS App 전체 다운로드 수 -> 전체 다운로드 수

* 푸터에 creator 행간이 좀더 넓었으면 좋겠당

@dev-seomoon

**Comment by dev-seomoon** [comment]
추가로 다음 작업도 진행 예정!
+) News 페이지 아티클 링크, 이미지 변경
전체 다운로드 수 380,000으로 변경
다운로드 버튼 모바일 반응형 배치 변경

**Comment by zion830** [comment]
@dev-seomoon 
아티클 아무나 수정할수 있게 구글 스프레드 시트랑 연동해서 자동으로 불러오게 하는거 가능..? ㅎㅎ
https://ichi.pro/ko/seupeuledeu-siteulo-gudongdoeneun-react-web-aeb-eul-mandeuneun-bangbeob-110538779539886

**Comment by dev-seomoon** [comment]
@zion830 한 번 시도는 해볼께..ㅎㅎ

**Comment by dev-seomoon** [comment]
- News 페이지 아티클 링크, 이미지 변경

빼고 전부 수정 & 배포 완료

**Comment by dev-seomoon** [comment]
아티클 이미지 크기 332 x 180 px이나 664 x 360px 로 맞춰야 함

**Comment by zion830** [comment]
이거 내가 편집해서 주면 되는거야?

**Comment by dev-seomoon** [comment]
아 맞다 써놓고 말하는거 잊어버렸네..! 응 가능하면 저렇게 편집 부탁해..!

**Comment by dev-seomoon** [comment]
지금 배포돼있는거랑 동일한 아티클 사진은 따로 안보내도돼 있는거 쓰면 되니까!
바쁘면 내가할께!
